const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const s=fs.readFileSync(path.join(__dirname,'..','slurry','index.html'),'utf8').split('<script>')[1].split('// ---------- WGSL ----------')[0],m={exports:{}};
new Function('module',s+'\nmodule.exports={MachineSystem,Engine,makeParams,lightHeat,mkLife,mkCargo,cargoFraction};')(m);
const{MachineSystem,Engine,makeParams,lightHeat,mkLife,mkCargo,cargoFraction}=m.exports;
const c=new MachineSystem(100,60);assert(c.place('turbine',12,20));
for(const x of[30,45,60])assert(c.place('light',x,20));assert(!c.place('light',30,20));
c.wireLine(17,20,27,20);c.wireLine(33,20,42,20);c.wireLine(48,20,57,20);
c.rotors[0].power=1;c.logicStep();assert(c.lights.filter(Boolean).every(l=>l.on));
c.rotors[0].power=0;c.logicStep();assert(c.lights.filter(Boolean).every(l=>!l.on));
c.rotors[0].power=1;c.erase(38,20,.2);c.logicStep();assert(c.lights[0].on);assert(!c.lights[1].on&&!c.lights[2].on);
c.wireLine(33,20,42,20);c.logicStep();assert(c.lights[2].on);
c.erase(45,20,.2);c.logicStep();assert(!c.lights[1]&&!c.lights[2].on);assert.equal(c.map[20*100+45],0);
c.clear();assert(!c.lights.some(Boolean));assert(!c.map.some(Boolean));
const rev=new MachineSystem(80,50);rev.place('turbine',60,20);rev.place('light',30,20);rev.wireLine(65,20,65,10);rev.wireLine(65,10,33,10);rev.wireLine(33,10,33,20);rev.rotors[0].power=1;rev.logicStep();assert(rev.lights[0].on);
console.log('PASS chained lights, either terminal, power loss without latching, cut wires, erase and clear');
const P=makeParams({gy:0,jitter:0,steamP:1,meltIce:1,meltSnow:1,meltP:1,igniteP:1,powderP:1,dryP:1,blastP:1});
for(const [from,to] of[[1,15],[2,2],[5,4],[9,4],[14,1],[13,1],[6,1],[12,11],[3,3],[10,10],[18,18]])assert.equal(lightHeat(from,P,0).attr&31,to);
assert(lightHeat(2,P,0).attr&(1<<30));assert(lightHeat(5,P,0).blast===1);
const cargo=mkCargo(5,128,0);assert.equal(lightHeat(cargo,P,0).blast,cargoFraction(cargo));
assert.equal(lightHeat(mkLife(0,150),P,0).attr&31,6);assert.equal(lightHeat(mkLife(0x20,150),P,0).attr&31,16);
assert.equal(lightHeat(mkLife(0xffff,150),P,0).attr,mkLife(0xffff,150));
assert(!(lightHeat(mkLife(0,150)|32,P,0).attr&32));
console.log('PASS contact boiling/melting/ignition, explosive cargo fuel, thermophiles, immortality and thawing');
const lights=new MachineSystem(40,40);lights.place('light',20,20);const l=lights.lights[0],e=new Engine(40,40,100,P);
e.add(20,18.5,1);e.sort();const i=0;e.qx[i]=20;e.qy[i]=18.5;e.px[i]=20;e.py[i]=18.6;
lights.collide(e);assert.equal(e.attr[i]&31,1);assert(e.qy[i]<18.5);assert(e.py[i]-e.qy[i]<=1e-6);
l.on=true;lights.collide(e);assert.equal(e.attr[i]&31,15);
e.n=0;e.add(20,17.7,2);e.sort();lights.collide(e);assert(!(e.attr[0]&(1<<30)));
e.n=0;e.add(20,20,5);e.sort();lights.collide(e);assert.equal(e.attr[0]&31,4);assert.equal(e.blastOut.length,2);assert(Number.isFinite(e.px[0]+e.py[0]));
console.log('PASS solid unpowered body, contact-only heat and finite overlap collision');
const er=new Engine(40,40,100,makeParams({gy:0,jitter:0}));er.add(10,10,1);er.add(30,30,8);
er.step({kind:1,x:10,y:10,r:2,vx:0,vy:0,len:1});assert(!Array.from(er.attr.slice(0,er.n)).some((a,i)=>(a&31)&&er.qx[i]<15));assert(Array.from(er.attr.slice(0,er.n)).some(a=>(a&31)===8));
console.log('PASS eraser deletes particles within brush and preserves distant material');
